title: "Lalith Krishna Prakash Parsa"
description: "Ph.D. Applicant in Computer Science | AI • Data Analytics • Computer Vision"
theme: jekyll-theme-cayman
locale: en-US

url: "https://LkP23.github.io"
baseurl: "/lalith-portfolio"

author:
  name: "Lalith Krishna Prakash Parsa"
  email: "lalithprakash46@gmail.com"
  github: "https://github.com/LkP23"
  linkedin: "https://linkedin.com/in/lalithprakash"
  location: "Dallas, TX, USA"

markdown: kramdown
kramdown:
  input: GFM
permalink: pretty

include:
  - "_pages"
  - "assets"

defaults:
  - scope:
      path: ""
    values:
      layout: default
      css: "/assets/custom.css"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

favicon: "/assets/favicon.ico"
logo: "/assets/profile.jpg"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - "*.log"
