title: "Lalith Krishna Prakash Parsa"
description: "Ph.D. Applicant in Computer Science | AI • Data Analytics • Machine Learning"
theme: "minimal-mistakes-jekyll"
locale: "en-US"
minimal_mistakes_skin: "sunrise"   # modern colorful skin
logo: "/assets/profile.jpg"
repository: "LkP23/lalith-portfolio"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Lalith Krishna Prakash Parsa"
  avatar: "/assets/profile.jpg"
  bio: "Ph.D. Applicant in Computer Science focusing on AI, Data Analytics, and Computer Vision."
  location: "Dallas, TX"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lalithprakash46@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/LkP23"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lalithprakash"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
