# ==========================================================
# Lalith Krishna Prakash Parsa | Academic Portfolio (2025)
# ==========================================================

title: "Lalith Krishna Prakash Parsa"
description: "Ph.D. Applicant in Computer Science | AI • Data Analytics • Machine Learning"
locale: "en-US"

# --- THEME SETTINGS ---
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"   # options: default, air, mint, contrast, sunrise
logo: "/assets/profile.jpg"

# --- SITE URL ---
url: "https://LkP23.github.io"
baseurl: "/"

# --- AUTHOR INFORMATION ---
author:
  name: "Lalith Krishna Prakash Parsa"
  avatar: "/assets/profile.jpg"
  bio: "Ph.D. Applicant in Computer Science focusing on AI, Data Analytics, and Computer Vision."
  location: "Dallas, TX, USA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lalithprakash46@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/LkP23"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lalithprakash"

# --- MARKDOWN SETTINGS ---
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
future: true

# --- INCLUDE FOLDERS ---
include:
  - "_pages"

collections:
  pages:
    output: true

# --- DEFAULT PAGE SETTINGS ---
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
      read_time: false
      share: false
      show_date: false

# --- PLUGINS (GitHub Pages safe) ---
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# --- PAGINATION ---
paginate: 5
paginate_path: "/page:num/"

# --- NAVIGATION DATA DIRECTORY ---
data_dir: _data

# --- OPTIONS ---
search: true
comments: false
enable_darkmode: true
# ==========================================================
# Lalith Krishna Prakash Parsa | Academic Portfolio (2025)
# ==========================================================

title: "Lalith Krishna Prakash Parsa"
description: "Ph.D. Applicant in Computer Science | AI • Data Analytics • Machine Learning"
locale: "en-US"

# --- THEME SETTINGS ---
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"   # options: default, air, mint, contrast, sunrise
logo: "/assets/profile.jpg"

# --- SITE URL ---
url: "https://LkP23.github.io"
baseurl: "/"

# --- AUTHOR INFORMATION ---
author:
  name: "Lalith Krishna Prakash Parsa"
  avatar: "/assets/profile.jpg"
  bio: "Ph.D. Applicant in Computer Science focusing on AI, Data Analytics, and Computer Vision."
  location: "Dallas, TX, USA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lalithprakash46@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/LkP23"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lalithprakash"

# --- MARKDOWN SETTINGS ---
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
future: true

# --- INCLUDE FOLDERS ---
include:
  - "_pages"

collections:
  pages:
    output: true

# --- DEFAULT PAGE SETTINGS ---
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
      read_time: false
      share: false
      show_date: false

# --- PLUGINS (GitHub Pages safe) ---
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# --- PAGINATION ---
paginate: 5
paginate_path: "/page:num/"

# --- NAVIGATION DATA DIRECTORY ---
data_dir: _data

# --- OPTIONS ---
search: true
comments: false
enable_darkmode: true
