# ==========================================================
# Lalith Krishna Prakash Parsa | Portfolio (Primer Theme)
# ==========================================================

title: "Lalith Krishna Prakash Parsa"
description: "Ph.D. Applicant in Computer Science | AI • Data Analytics • Machine Learning"
theme: jekyll-theme-primer
locale: en-US

# --- SITE URL CONFIG ---
url: "https://LkP23.github.io"
baseurl: "/lalith-portfolio"

# --- AUTHOR INFO ---
author:
  name: "Lalith Krishna Prakash Parsa"
  email: "lalithprakash46@gmail.com"
  github: "https://github.com/LkP23"
  linkedin: "https://linkedin.com/in/lalithprakash"
  location: "Plano, Texas, USA"

# --- MARKDOWN SETTINGS ---
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty

# --- FILES & INCLUDES ---
include:
  - "_pages"
  - "assets"

# --- DEFAULT PAGE OPTIONS ---
defaults:
  - scope:
      path: ""
    values:
      layout: default
      css: "/assets/custom.css"

# --- PLUGINS SUPPORTED BY GITHUB PAGES ---
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# --- SOCIAL & SEO METADATA ---
social:
  name: "Lalith Krishna Prakash Parsa"
  links:
    - "https://github.com/LkP23"
    - "https://linkedin.com/in/lalithprakash"
    - "mailto:lalithprakash46@gmail.com"

favicon: "/assets/favicon.ico"
logo: "/assets/profile.jpg"

# --- EXCLUDE UNNECESSARY FILES ---
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - "*.log"
