# ─────────────────────────────────────────────
#  Site Identity
# ─────────────────────────────────────────────
title: "Lalith Krishna Prakash Parsa"
description: "Ph.D. Applicant in Computer Science | AI • Data Analytics • Machine Learning"
locale: en-US

url: "https://LkP23.github.io"
baseurl: "/lalith-portfolio"

# ─────────────────────────────────────────────
#  Author Information
# ─────────────────────────────────────────────
author:
  name: "Lalith Krishna Prakash Parsa"
  email: "lalithprakash46@gmail.com"
  github: "https://github.com/LkP23"
  linkedin: "https://linkedin.com/in/lalithprakash"
  location: "Dallas, TX, USA"

# ─────────────────────────────────────────────
#  Theme & Appearance
# ─────────────────────────────────────────────
theme: jekyll-theme-cayman
favicon: "/assets/favicon.ico"
logo: "/assets/profile.jpg"

# ─────────────────────────────────────────────
#  Markdown & Rendering
# ─────────────────────────────────────────────
markdown: kramdown
kramdown:
  input: GFM

permalink: pretty

# ─────────────────────────────────────────────
#  Directory Includes
# ─────────────────────────────────────────────
include:
  - "_pages"
  - "assets"

defaults:
  - scope:
      path: ""
    values:
      layout: default
      css: "/assets/custom.css"

# ─────────────────────────────────────────────
#  Plugins for GitHub Pages
# ─────────────────────────────────────────────
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# ─────────────────────────────────────────────
#  SEO Meta
# ─────────────────────────────────────────────
social:
  name: "Lalith Krishna Prakash Parsa"
  links:
    - "https://github.com/LkP23"
    - "https://linkedin.com/in/lalithprakash"

# ─────────────────────────────────────────────
#  Build Settings
# ─────────────────────────────────────────────
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - "*.log"
  - "*.zip"
  - "*.tmp"

# ─────────────────────────────────────────────
#  Customization
# ─────────────────────────────────────────────
sass:
  style: compressed

show_downloads: false
