# ==========================================================
# Lalith Krishna Prakash Parsa | Academic Portfolio (2025)
# Streamlined Jekyll Config (No index.md or home.md)
# ==========================================================

title: "Lalith Krishna Prakash Parsa"
description: "Ph.D. Applicant in Computer Science | AI • Data Analytics • Machine Learning"
locale: "en-US"

# --- THEME SETTINGS ---
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "sunrise"

# --- SITE URL ---
url: "https://LkP23.github.io"
baseurl: ""

# --- AUTHOR INFO ---
author:
  name: "Lalith Krishna Prakash Parsa"
  avatar: "/assets/profile.jpg"
  bio: "Ph.D. Applicant in Computer Science | AI, Data Analytics, and Machine Learning"
  location: "Dallas, TX, USA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/LkP23"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lalithprakash"

# --- MARKDOWN SETTINGS ---
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
future: true

# --- INCLUDE FOLDERS ---
include:
  - "_pages"

collections:
  pages:
    output: true

# --- DEFAULT PAGE SETTINGS ---
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
      toc: true
      toc_label: "On this page"
      toc_sticky: true
      read_time: false
      share: false
      show_date: false
      css: /assets/clean.css

# --- PLUGINS ---
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# --- PAGINATION ---
paginate: 5
paginate_path: "/page:num/"

# --- NAVIGATION MENU (from _data/navigation.yml) ---
data_dir: _data

# --- OPTIONS ---
search: true
comments: false
enable_darkmode: true

# --- EXCLUSIONS (hide unnecessary files like README.md) ---
exclude:
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - vendor

# --- SEO & META ---
social:
  name: "Lalith Krishna Prakash Parsa"
  links:
    - "https://github.com/LkP23"
    - "https://linkedin.com/in/lalithprakash"

# --- FOOTER SETTINGS ---
footer:
  links:
    - label: "Back to Top"
      icon: "fas fa-arrow-up"
      url: "#top"
