# ==========================================================
# Lalith Krishna Prakash Parsa | Academic Portfolio (2025)
# GitHub Pages Configuration for Minimal Mistakes Jekyll
# ==========================================================

title: ""
description: ""
locale: "en-US"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"    # soft & clean skin
logo: "/assets/profile.jpg"
repository: "LkP23/lalith-portfolio"

url: "https://LkP23.github.io"
baseurl: "/lalith-portfolio"

author:
  name: "Lalith Krishna Prakash Parsa"
  avatar: "/assets/profile.jpg"
  bio: "Ph.D. Applicant in Computer Science focusing on AI, Data Analytics, and Computer Vision."
  location: "Dallas, TX, USA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lalithprakash46@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/LkP23"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lalithprakash"

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
future: true

include:
  - "_pages"

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      sidebar: false
      css: /assets/custom.css
      read_time: false
      share: false
      show_date: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

paginate: 5
paginate_path: "/page:num/"

search: true
comments: false
enable_darkmode: false
