# ==========================================================
# Lalith Krishna Prakash Parsa | Academic Portfolio (2025)
# GitHub Pages configuration with Minimal Mistakes Theme
# ==========================================================

title: "Lalith Krishna Prakash Parsa"
description: "Ph.D. Applicant in Computer Science | AI • Data Analytics • Machine Learning"
locale: "en-US"

# Theme configuration
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "sunrise"     # colorful, modern skin
logo: "/assets/profile.jpg"
repository: "LkP23/lalith-portfolio"

# ==========================================================
# Author Information
# ==========================================================
author:
  name: "Lalith Krishna Prakash Parsa"
  avatar: "/assets/profile.jpg"
  bio: "Ph.D. Applicant in Computer Science focusing on AI, Data Analytics, and Computer Vision."
  location: "Dallas, TX, USA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lalithprakash46@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/LkP23"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lalithprakash"

# ==========================================================
# Build Configuration
# ==========================================================
url: "https://LkP23.github.io"
baseurl: "/lalith-portfolio"
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

include:
  - "_pages"

collections:
  pages:
    output: true

# ==========================================================
# Default Settings for Pages
# ==========================================================
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
      css: /assets/custom.css
      read_time: false
      share: false
      show_date: false

# ==========================================================
# Pagination and Analytics (Optional)
# ==========================================================
paginate: 5
paginate_path: "/page:num/"
google_analytics: ""

# ==========================================================
# Permalinks and Sitemap
# ==========================================================
permalink: /:categories/:title/
future: true

# ==========================================================
# Social Media Preview / SEO
# ==========================================================
social:
  name: "Lalith Krishna Prakash Parsa"
  links:
    - "https://github.com/LkP23"
    - "https://linkedin.com/in/lalithprakash"

# ==========================================================
# Theme Enhancements
# ==========================================================
comments: false
search: true
enable_darkmode: true
highlighter: rouge
