# ==========================================================
# Lalith Krishna Prakash Parsa | Academic Portfolio (2025)
# ==========================================================

title: "Lalith Krishna Prakash Parsa"
description: "Ph.D. Applicant in Computer Science | AI • Data Analytics • Machine Learning"
locale: "en-US"

# --- THEME SETTINGS ---
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "teal"

logo: "/assets/profile.jpg"
repository: "LkP23/lalith-portfolio"

# --- SITE URL CONFIG ---
url: "https://LkP23.github.io"
baseurl: "/lalith-portfolio"

# --- AUTHOR PROFILE ---
author:
  name: "Lalith Krishna Prakash Parsa"
  avatar: "/assets/profile.jpg"
  bio: "Ph.D. Applicant in Computer Science focusing on AI, Data Analytics, and Computer Vision."
  location: "Dallas, TX, USA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lalithprakash46@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/LkP23"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lalithprakash"

# --- PLUGINS ---
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
permalink: /:title/

include:
  - "_pages"
  - "_data"

collections:
  pages:
    output: true

# --- NAVIGATION ---
navigation:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research/"
  - title: "Publications"
    url: "/publications/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "CV"
    url: "/cv/"
  - title: "Contact"
    url: "/contact/"

# --- THEME OVERRIDES ---
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: splash
      author_profile: false
      classes: wide
      header:
        overlay_color: "#000"
        overlay_filter: "0.45"
        overlay_image: "/assets/banner.png"
      css: "/assets/custom.css"
