# ==========================================================
# Lalith Krishna Prakash Parsa | Academic Portfolio (2025)
# ==========================================================

title: ""
description: "Ph.D. Applicant in Computer Science | AI • Data Analytics • Machine Learning"
locale: "en-US"

# --- THEME SETTINGS ---
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "sunrise"
logo: ""

# --- SITE URL ---
url: "https://LkP23.github.io"
baseurl: "/"

# --- AUTHOR INFO (avatar only) ---
author:
  name: ""
  avatar: "/assets/profile.jpg"
  bio: ""
  location: ""
  links: []

# --- MARKDOWN SETTINGS ---
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
future: true

# --- INCLUDE FOLDERS ---
include:
  - "_pages"

collections:
  pages:
    output: true

# --- DEFAULT PAGE SETTINGS ---
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
      read_time: false
      share: false
      show_date: false

# --- PLUGINS (GitHub Pages safe) ---
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# --- PAGINATION ---
paginate: 5
paginate_path: "/page:num/"

# --- NAVIGATION DATA DIRECTORY ---
data_dir: _data

# --- OPTIONS ---
search: true
comments: false
enable_darkmode: true
