# ==========================================================
# Lalith Krishna Prakash Parsa | Academic Portfolio (2025)
# GitHub Pages Jekyll Configuration (Remote Theme)
# ==========================================================

title: "Lalith Krishna Prakash Parsa"
description: "Ph.D. Applicant in Computer Science | AI • Data Analytics • Machine Learning"
locale: "en-US"

# --- THEME SETTINGS ---
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "sunrise"    # colorful theme with light/dark support
logo: "/assets/profile.jpg"
repository: "LkP23/lalith-portfolio"

# --- SITE URL CONFIGURATION ---
url: "https://LkP23.github.io"
baseurl: "/lalith-portfolio"

# --- AUTHOR INFORMATION ---
author:
  name: "Lalith Krishna Prakash Parsa"
  avatar: "/assets/profile.jpg"
  bio: "Ph.D. Applicant in Computer Science focusing on AI, Data Analytics, and Computer Vision."
  location: "Dallas, TX, USA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lalithprakash46@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/LkP23"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lalithprakash"

# --- MARKDOWN AND BUILD SETTINGS ---
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
future: true

# --- FOLDERS TO INCLUDE ---
include:
  - "_pages"

collections:
  pages:
    output: true

# --- DEFAULTS FOR ALL PAGES ---
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
      css: /assets/custom.css
      read_time: false
      share: false
      show_date: false

# --- PLUGINS ---
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

# --- PAGINATION SETTINGS ---
paginate: 5
paginate_path: "/page:num/"

# --- SEO AND SOCIAL LINKS ---
social:
  name: "Lalith Krishna Prakash Parsa"
  links:
    - "https://github.com/LkP23"
    - "https://linkedin.com/in/lalithprakash"

# --- OPTIONS ---
search: true
comments: false
enable_darkmode: true
