title: "Lalith Krishna Prakash Parsa"
description: "Ph.D. Applicant in Computer Science | AI • Data Analytics • Machine Learning"
baseurl: ""
url: "https://LkP23.github.io"
markdown: kramdown
permalink: pretty
